### ISSUE TITLE
Functions like `InputFloat2` should accept pointer-to-array arguments

### ISSUE THREAD

**Issue by kecman** [kevinw/jai-imgui#3]
This came up in the discord: https://discord.com/channels/661732390355337246/661732390355337249/798950258636750858

I hit this with the linux module that comes with the compiler and I recall you said you'd fix it, but when I looked (to confirm what the fix was) I noticed you hadn't. So...err, this is a reminder ^_^

**Comment by kevinw** [comment]
Thanks for the reminder! Fixed in 4e6d3da0472f1da82bcff527c1ca38ebb88ff8df
