### ISSUE TITLE
d3d11_shader not found

### ISSUE THREAD

**Issue by TooManyDots** [kevinw/jai-imgui#5]
Hi,
The directx 11 exampkle imports some file called "d3d11_shader". I can't find the file in either this repo or the jai-modules. Is that file generated somehow or just missing?

**Comment by kevinw** [comment]
That’s an oversight, I’ll make sure the example works within a day or two. Thanks for reporting!

**Comment by kevinw** [comment]
OK should be fixed! Let me know if `jai build_examples.jai && example_d3d11.exe` doesn't work for you.
